### ISSUE TITLE
Compile to C

### ISSUE THREAD

**Issue by Kinrany** [PXshadow/OpenLife#1]
Is there a C target for Haxe?

I kinda want to write my own client in Rust, but without rewriting a substantial portion of the code.

**Comment by PXshadow** [comment]
There is a c/hashlink target for haxe. https://github.com/HaxeFoundation/hashlink I'm not sure how embeded the c bindings are to hashlink if no ndlls could be used. I will get the api finished tomorrow and I can send you the generated c code and see if it's possible or how much would be needed to be changed to fit your use case.

**Comment by PXshadow** [comment]
[src.zip](https://github.com/PXshadow/OpenLife/files/3977066/src.zip)
Here is my first attempt to generate c bindings, keep in mind the method to use it is GCC and it may require hdll files, I'm not quite sure though, here's a link with a little more info https://haxe.org/manual/target-hl-c-compilation.html

**Comment by Kinrany** [comment]
Nice, thanks :D

**Comment by PXshadow** [comment]
Any news on this?

**Comment by Kinrany** [comment]
Not really, sorry :(

I'm permanently stuck in the limbo of starting new projects before making any substantial progress :0

**Comment by PXshadow** [comment]
I've been there no worries, hard to find your footing as a programmer sometimes with longterm projects.
