### ISSUE TITLE
GameSource directory necessity after data setup

### ISSUE THREAD

**Issue by connorhsm** [PXshadow/OpenLife#10]
Nice catch with the delete dir folder, as for removing GameSource right after, I beleive it's only needed for the client side and therefore could be avoided downloading altogether if only using the openlife client. Let me know what you think is best.

_Originally posted by @PXshadow in https://github.com/PXshadow/OpenLife/issues/9#issuecomment-1126785927_

**Comment by connorhsm** [comment]
@PXshadow Does the GameSource directory need to remain in place once the data setup has run for the client or is it not required, just like for the server?

**Comment by connorhsm** [comment]
I've commented out all processing related to GameSource before running setup data for the server and theres no issue with the server.

The better solution may be to have different setup scripts for the client and server.

**Comment by PXshadow** [comment]
> The better solution may be to have different setup scripts for the client and server.

I completely agree it also depends if the client is headless (non visual) or visual. I think the settings folder is used for both types of clients for backwards compatibility of client settings. The rest are only needed for a visual client:
* graphics (ui graphics such as mouse cursor, bottom ui bar etc)
* groundTileCache (ground graphics after preprocessing such as blurring and tiling)
* languages (all game text in English useful to use 3rd party .txt for other languages and include into the visual client)
