### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MaDc0wUSP** [PXshadow/OpenLife#2]
It would be nice to be able to select the executable for each mod client.
A button maybe below "Folder" or if the Folder button can't find clients/clientname instead of an error, it could bring up a "choose executable" for that client.

-Meth

**Comment by PXshadow** [comment]
Are you thinking the executable are inside of the generated data folder? Currently the launcher separates the data and the client from each other in order to allow mix and matching, but I am open to a change in the architecture if it'd be more friendly.
